### ISSUE TITLE
Tracking Failed, Running detached from tty

### ISSUE THREAD

**Issue by jonesm2** [GitSquared/edex-ui#224]
Hi, 

First off, I'm really enjoyed edex, so thank you!

I'm getting a "Tracking Failed, Running detached from tty" message on the file list next to the keyboard.

Running on Windows 10.
Am I missing a permission or setting?

**Comment by GitSquared** [comment]
Glad you enjoy it!

eDEX tracks the terminal's CWD (current working directory) to display the folder you're currently in. Sadly i couldn't find a way to do this on Windows, which is why the display runs "detached".

Finding a better solution for this is on my long-term roadmap. In the meantime, i'm afraid you'll have to skip on this feature.

The display should still be functional, though.

**Comment by jonesm2** [comment]
No problem at all, thought it worth a mention.

Thanks again, looking forward to more updates over time.

**Comment by GitSquared** [comment]
Yeah you were right to report this anyway, i should include a note about this in the readme FAQ.

**Comment by JaroslawPokropinski** [comment]
Hey, I think that I solved this using windows-tlist dependency from tlist. It doesnt work with powershell but works with cmd just fine (powershell doesnt actualy change cwd with cd command). Should I make an pull request?

**Comment by GitSquared** [comment]
@JaroslawPokropinski Sure, go ahead! I'll definetly look into it.
