### ISSUE TITLE
Bindings to hide keyboard

### ISSUE THREAD

**Issue by MagixInTheAir** [GitSquared/edex-ui#259]
I believe a good enhancement would be to have a configurable key binding to hide the virtual keyboard (or remove key highlights) in order to be able to record commands which need a password

**Comment by GitSquared** [comment]
eDEX doesn't use any key bindings or shortcut yet, but this might be an interesting idea.

Related discussion on Hacker News: 
![untitled](https://user-images.githubusercontent.com/24496417/48944771-61013700-ef28-11e8-8538-f775329b82d1.png)

I'm open to ideas about how we should implement this. Perhaps do a global "safe-mode" that blurs stuff such has keyboard keys and IPv4 info?

**Comment by clragon** [comment]
Would be nice to have a config to just hide the keyboard and show something alternatively, for devices that won't ever have touch. Maybe just enlarge the file browser.

**Comment by GitSquared** [comment]
Yeah i'll make a theme for that soon. Should take 'bout a minute but i'm busy with more pressing issues.

**Comment by rslay** [comment]
Just want to say, this can be easily done with the [injectCSS](https://github.com/GitSquared/edex-ui/wiki/Themes#injectcss-hack-away) feature that is available, try opening your [userData](https://github.com/GitSquared/edex-ui/wiki/userData)/themes folder and make a copy of `tron-typeleft.json` and change at the bottom the `section#keyboard{...}` section to `section#keyboard{display:none;}`.

I'm aware this is a bit of a hack since the keyboard is still there, just not rendered by electron.
I'll try making a pull request to add a `tron-nokeyboard.json` theme, @GitSquared let me know if this is an OK solution for now.

**Comment by GitSquared** [comment]
@rslay yeah that was what i was going to do anyway, using injectCSS.

Perhaps you could also expand the filesystem display to fill all the space. PRs welcome.

**Comment by GitSquared** [comment]
Closed because of #288

**Comment by planetahuevo** [comment]
Can you explain how to do this a little bit more, I am not sure I understood the instructions. 

Thanks!
