### ISSUE TITLE
Implementing an internal update mechanism

### ISSUE THREAD

**Issue by Neltherion** [GitSquared/edex-ui#278]
Hi,

Is there any plans to implement a mechanism for managing updates internally? The way I see it, right now we have to download the binary each time there's a new change, right?

Thanks for the awesome app!

**Comment by GitSquared** [comment]
Currently there is the [updateChecker](https://github.com/GitSquared/edex-ui/blob/master/src/classes/updateChecker.class.js) module that will spawn a message if a newer version has been detected on GitHub Releases.

I thought about including auto-updating a while back (see #98), but didn't think it would be worth it, mostly because i was planning to release eDEX as a finished software, patch up a few bugs post-release and then just never touch the thing again.

That said, seeing how things have spiraled out of control since last Tuesday, an automatic updater might actually be an interesting feature. I'll keep this one on the ever-expanding roadmap.

**Comment by GitSquared** [comment]
I'm gonna have to drop this, [lengthy explanation/rant available on my newly created blog](https://squared.codebrew.fr/posts/code-signing/).
