### ISSUE TITLE
File Check freezes on startup

### ISSUE THREAD

**Issue by erixom** [GitSquared/edex-ui#365]
Hi and Merry Christmas, 
So when I start EDEX on both my PC (Win 10) and my laptop (Win 7) it goes through startup normally but then gets stuck with the terminal on a blank screen and file check "checking available space". I don't know if that's just an issue for me, and it's just a minor issue but thought you might want to be aware. 
Video: https://drive.google.com/file/d/1lSnUQQGppLJK5u0a-7sGg11k5vH-aXb3/view
I looked but couldn't find this anywhere else,
Thanks!

**Comment by GitSquared** [comment]
Hey and Merry Christmas to you too!

Yes, I'm aware of this issue. On startup, the first time the underlying shell process outputs anything to eDEX, it starts up a background routine that tries to "synchronise" the shell's working directory and eDEX's filesystem module - this particular feature is not available on Windows, sadly, so it falls back to a standalone file browser instead.

Due to a bug in `node-pty`, the particular library used to spawn & communicate with the shell process, it doesn't output anything until you start typing in it. Hence why the filesystem module is frozen until you start using the term. This is only happening on Windows.

Can you confirm you were running v1.1.2 downloaded from the Releases page (prebuilt bins)? In the upcoming 2.0 version `node-pty` has been upgraded and I believe this bug is gone, so I just want to confirm that you experienced it on an old release.

Thanks for raising the issue.

**Comment by erixom** [comment]
Correct, 1.1.2. Thanks :)

**Comment by GitSquared** [comment]
All right. I'll keep this open and try to confirm whether it has been fixed or not ASAP.

**Comment by GitSquared** [comment]
So, it seems that the `node-pty` update didn't fix anything yet.
I've implemented a workaround for this which is that the filesystem immediately starts parsing the default beginning working directory as defined in eDEX's [settings](https://github.com/GitSquared/edex-ui/wiki/settings.json), to avoid the "freeze" effect.

As soon as the terminal is initialized the routine described above takes place.
