### ISSUE TITLE
Cannot find module 'signale'

### ISSUE THREAD

**Issue by wsturgiss** [GitSquared/edex-ui#367]
Running on MacOS from the repo.  Cloned the repo, ran `npm install`, then `npm start`, and it can't find a module called signale which appears to be referenced several times.  

As others have said, this is an amazing project and let me know if there's anything I can do to help out, including any more information about this issue.  Love what you have made.

**Comment by GitSquared** [comment]
As written in the README, you need to run `npm run install-linux` to install all dependencies correctly before running from source - this is because this repo uses two `package.json` files & native modules that needs to be built against your specific system.

Cheers. I could actually use some help, if you're running from source, could you confirm that #366 has been fixed?

**Comment by wsturgiss** [comment]
Oh, I see.  Silly mistake, me leaving out the last step.  Thanks for addressing that.  However, even after doing a fresh clone, then `npm install`, and then `npm run build-linux` as stated in the readme I get the same issue.  However, in your comment you suggest running `npm run install-linux`, and that worked.  I think the readme ought to be updated to change `npm run build-linux` to `npm run install-linux'

**Comment by GitSquared** [comment]
I believe the README's correct, actually - it's just not the same commands whether you're looking to run from source or to build packaged binaries.

Read the file again if you're still confused, i'll admit the formatting gone a bit wrong since I had to add the oblivious warning for lambda users trying to mess with the code instead of downloading releases.

**Comment by wsturgiss** [comment]
Oh I see, I did misread it.  I was building a binary.  Thanks.
