### ISSUE TITLE
Switching disk failure

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#433]
![screenshot_1](https://user-images.githubusercontent.com/11785085/52917203-e35f8400-32e8-11e9-9018-b0eb87d2f10a.png)

When clicking `Show Disks` and selecting a disk, this results in an immediate failure of the Filesystem.
The Filesystem also will be unusable even when switching tabs.
A restart is required to make it working again.

It would be nice if the Filesystem would reinitialize when switching a tab.
There also seems to be an issue with printing a command into the terminal. 

Clicking the Disk in the Show Disk menu did result in a command being printed, but it failed with `Syntax error` while the command itself was correct.

**Comment by GitSquared** [comment]
Switching disks might not be correctly implemented for detached mode indeed. Will look into it.

**Comment by GitSquared** [comment]
This is actually quite a difficult one. I can't find out why it's failing, the paths should be readable.

**Comment by GitSquared** [comment]
See also: #262 #235

**Comment by GitSquared** [comment]
I had to look in-depth for this one but finally fixed it.
Technical rundown for future reference:
- The drive list does not put a trailing anti-slash when giving drive paths (eg. outputs `C:` instead of `C:\`), which caused `fs.readdir` to output the content of eDEX's CWD instead of the actual path, because of some weird low-level API behavior. Fix:
  - https://github.com/GitSquared/edex-ui/blob/7c65c1b4e1717b8e29d87c5a3c3d347cb38c581c/src/classes/filesystem.class.js#L138
- When reading some system entries like swapfile and volume information directories, `lstat` was rejected (`EBUSY` or `EPERM` errors) which caused the whole reader to put the display in failed state. Those errors are now silently ignored, and files that caused them are applied a special `system` type:
  - https://github.com/GitSquared/edex-ui/blob/7c65c1b4e1717b8e29d87c5a3c3d347cb38c581c/src/classes/filesystem.class.js#L158-L162
  - https://github.com/GitSquared/edex-ui/blob/7c65c1b4e1717b8e29d87c5a3c3d347cb38c581c/src/classes/filesystem.class.js#L171-L191
- The code that prevented the apparition of a `Go up` item on root directories was not working correctly for windows, I added a regex in the condition that match the `C:\` path format:
  - https://github.com/GitSquared/edex-ui/blob/7c65c1b4e1717b8e29d87c5a3c3d347cb38c581c/src/classes/filesystem.class.js#L222-L227
- Finally, those `system`-type files and folders have no click actions to prevent trying to access swap or limited permission paths:
  - https://github.com/GitSquared/edex-ui/blob/7c65c1b4e1717b8e29d87c5a3c3d347cb38c581c/src/classes/filesystem.class.js#L312-L314
  - They also take the same "gear" icon as eDEX's settings file:
https://github.com/GitSquared/edex-ui/blob/7c65c1b4e1717b8e29d87c5a3c3d347cb38c581c/src/classes/filesystem.class.js#L356-L359

And this is it. Will fix the patch in the next release - I'm probably going to ship a `v2.1.1` hotfix within the next few weeks. Patch is already available if you're running from source, of course.

**Comment by clragon** [comment]
Okay this is epic.

I really love how you take your time to fix every issue, I just hope I dont annoy you when opening so many everytime I check on the project.

**Comment by GitSquared** [comment]
@clragon I'm glad you do actually. Your reports have helped the project a lot already. Keep it up my man. :v:
