### ISSUE TITLE
Feature Request: Optional LCARS theme.

### ISSUE THREAD

**Issue by Xeddius** [GitSquared/edex-ui#456]
There is an open-source LCARS-SDK on github located [Here](https://github.com/Aricwithana/LCARS-SDK).
It would be amazing to see this implemented as this would make for a fun and usable LCARS terminal for the many Trek fans out there! Understandably this could take quite some time to do, but all of the specifications are in the LCARS-SDK and there are vector assets which should make it simple to scale to any dpi/resolution.

**Comment by GitSquared** [comment]
I actually didn't know about LCARS since I'm not much of a Star Trek fan. It's pretty rad, and the SDK you linked looks pretty complete.

However, I think it differs too much from eDEX to be included in this project: implementing an LCARS theme would be a hell of a lot of work and require a solid bit of research, and making it optional would bloat the software for users not interested in it - as well as make the codebase significantly harder to maintain.

I might look into it for another project or a hacky "extension", though. Thanks for reaching out about this.
