### ISSUE TITLE
Can You explain?

### ISSUE THREAD

**Issue by pabit** [GitSquared/edex-ui#465]
![Selection_048](https://user-images.githubusercontent.com/15835569/54723766-f4f6ae80-4b68-11e9-8187-63f4645cfe24.png)

**Comment by GitSquared** [comment]
Must be a false positive...?
Check on VirusTotal or something else to see how many antivirus software report this.

I believe no security issue of this importance has been found in eDEX's dependencies since the last release, and I'm monitoring those actively, so it can't come from there. The code itself is of course open-source and if you don't trust the pre-packaged binaries you can build them yourself.

**Comment by GitSquared** [comment]
https://www.virustotal.com/#/file/b46093d3f712d2288ea8034e586e6479984016b005f728431caa8986ac7df5d3/detection

I think it's all good. Feel free to reopen if you have any further questions.
