### ISSUE TITLE
The network is offline in windows. How to enable that?

### ISSUE THREAD

**Issue by diptampaul** [GitSquared/edex-ui#503]
(...)

**Comment by GitSquared** [comment]
@diptampaul Open the settings (`Ctrl+Shift+S`). On `iface`, use the dropdown menu to select the right network interface - you'll want to avoid virtualization (VMware) stuff, and select something like `Wi-Fi` or `Ethernet`.

Then, on the lower part of the window, hit `Save to Disk` and `Reload UI`. Should work now.

**Comment by fir0j** [comment]
![DeepinScreenshot_20190512093759](https://user-images.githubusercontent.com/41787040/57577658-d1c9ea80-7499-11e9-895f-566112fc9385.png)
I am on Deepin Linux. Though Correct interface has been detected, Network status, World View, Network Traffic all showing offline. But Ping 8.8.8.8 is working fine in terminal.

What's the issue with my system? please take a look

**Comment by fir0j** [comment]
One Strange thing i found, When i am connecting my laptop with mobile hotspot then Network status = ONLINE that is it's EDex-ui is  working fine but when i am connected to my wifi router it's showing Network status = OFFLINE even if it's detecting correct interface and ping is working termnal too.

**Comment by rinku98** [comment]
same here on windows

**Comment by rinku98** [comment]
It doesn't work now with a wifi roueter neither a mobile hotspot

**Comment by clragon** [comment]
Is it stated somewhere that you can open the settings with `ctrl+shift+s`?
because I havent been able to find that until I've now seen that comment. I did notice though that you can open it by clicking the file, also that json editor is pretty fucking neatly designed ngl, would even be nice as a general thing 👀

**Comment by fir0j** [comment]
> It doesn't work now with a wifi roueter neither a mobile hotspot

it does work when i connect my laptop to my mobile's hotspot. Don't why? but  ya it works

**Comment by GitSquared** [comment]
@clragon It is stated in the [Settings wiki page](https://github.com/GitSquared/edex-ui/wiki/settings.json) - there's also a keyboard shortcuts article in the wiki.

In latest versions you can use `Ctrl+Shift+K` to open a pop-up with a list of available keyboard shortcuts. By the way, these work whether you're using a physical keyboard or eDEX's touch-enabled one.

**Comment by GitSquared** [comment]
@fir0j @rinku98 3 things can cause eDEX to display the network as "offline" when it is not:

- The automatic interface selection script might have failed to detect the correct interface
- The IP address used for latency testing (default `1.1.1.1`) might be unreachable, possibly because of a proxy/firewall block
- The geoip API backend (`ipinfo.now.sh`, also made by me) might be unreachable (see possible reasons above, although it is more likely to be offline than the latency IP - that said, we're rocking a solid 100% uptime worldwide since 6 months)

You can use the settings to override the network interface and the latency testing address.
Currently you cannot point eDEX to another geoip backend.

First thing i'd advise to check if you're confident the network interface is good:

- Is eDEX blocked by your firewall?
- Do you use a network proxy?
- Does accessing `ipinfo.now.sh` in a browser work?

And, worst case scenario, try and open the dev tools (`Ctrl+Shift+I`) and if anything pops up in the "console" tab, report to me. :wave:

**Comment by fir0j** [comment]
@GitSquared 
* don't use network proxy
output for `ipinfo.now.sh `  what i got is `{"api_version":"3.0.0","geo":{"latitude":12.9833,"longitude":77.5833,"metro_code":null,"time_zone":"Asia/Kolkata"},"ip":"115.99.87.169","time":1557918541}`

* i have no idea if eDEX is blocked by firewall. How to check?

* while i am doing `ping 1.1.1.1` in eDEX terminal, i am able to get reply. it's working there but still Network status is OFFLINE

* i even tried `8.8.8.8` in eDEX terminal instead of '1.1.1.1' . But still no luck

* i am repeating again WHY THE HELL eDEX IS WORKING WHEN I CONNECTING MY LAPTOP TO MOBILE HOTSPOT ? . I Would be more than happy if you answer.

THNKS FOR YOUR REPLY

**Comment by GitSquared** [comment]
@fir0j I can't tell you how to check your firewall or even if you have one at all, I don't know how your system is configured/what you've installed - especially if you're on Linux.

Regarding the mobile hotspot thing, I have no idea. Maybe your laptop is using a different network interface when you switch to the hotspot. Maybe there's a configuration somewhere that prevents eDEX from accessing the Internet through your router.

All I can tell you is that I'm confident the issue is not coming from my software, and as such there's nothing I can do.

**Comment by eajazahmed022** [comment]
How Can I Connect VMware to eDex UI , I  am a newbie .

**Comment by rikmac** [comment]
In ping Addr / IPv4 address to test Internet connectivity / put the address of your router eg.  192.168.1.1 or whatever your address is, it worked for me.

**Comment by KyrinCode** [comment]
> In ping Addr / IPv4 address to test Internet connectivity / put the address of your router eg. 192.168.1.1 or whatever your address is, it worked for me.

Stille not working for me on Mac 10.14.6

**Comment by MEQinJi** [comment]
> > It doesn't work now with a wifi roueter neither a mobile hotspot
> 
> it does work when i connect my laptop to my mobile's hotspot. Don't why? but ya it works

did your roueter run S-S or something like that? if it did, this might happened. try run S-S on full proxy mode, or turn it off.
