### ISSUE TITLE
Incompatibility with shadowplay

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#525]
## Technical information
**Using version:**
 - `latest` (latest release, currently `v2.2.2`)

**Running on:**
 - Windows

**How comfortable you are with your system and/or IT in general:**
 - My machine is fully under my control, tell me what you need

---

Trying to use shadowplay with edex is impossible. Opening the overlay results in the mouse stopping to react and edex starting to flicker alot. It is impossible to record edex, too, since for some reason the resulting video (if you manage to make a recording by controlling the overlay with the arrow keys) will be just a black screen.

![Edex-ui Screenshot 2019 06 09 - 11 50 18 99](https://user-images.githubusercontent.com/11785085/59157564-1e124580-8aad-11e9-838e-12b9d1605677.png)

**Comment by GitSquared** [comment]
The ShadowPlay overlay is made for GPU-rendered applications. While eDEX's Chromium renderer uses the GPU for some rendering tasks (hardware acceleration, which is a pretty obscure process that varies a lot between implementations and what hardware it's running on), it does not provide a fully GPU-rendered window.

The real bug here is that the overlay appears at all, as it does not support this kind of applications (web browsers, that is) - afaik.

Either way there is nothing I can do at this level. Out of curiosity, does setting eDEX in windowed mode (activate `allowWindowed` setting, then press `F11`) resolves the flicker issue with ShadowPlay?
