### ISSUE TITLE
Non-fullscreen option that only shows System and Network panels

### ISSUE THREAD

**Issue by chaseWilliams** [GitSquared/edex-ui#579]
**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [x] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [x] Would need some work, but nothing impossible.
- [ ] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

I would love to just have this popped up on my monitor showing system usage and network statistics - it looks way cooler and is more useful than the default macOS activity monitor. That being said, I'm not sure how hard it would be to have an option to transition this to a widget app, rather than a full blown terminal emulator. 

The `tron-notype` theme is a good start for what I envision, but it'd also have to be non-fullscreen and disable the filesystem and terminal panels. Is this a possibility at all?

**Comment by GitSquared** [comment]
To transform this into a widget app, you'd have to make two different windows for each panel so you can put actual apps in-between.

This is not overly complicated to do and would require only deleting a whole bunch of code and moving some around, but I don't think it would make sense to do all this as an option in the app. eDEX *is* a terminal emulator, not a widget.

So I'm willing to give some guidance if you wish to fork this project and make it a widget, but I won't do that on the main branch myself.

**Comment by chaseWilliams** [comment]
If I were to fork and do this myself, any pointers for what I would need to do? I have worked a little bit with electron before, but that was only in following a tutorial essentially.

**Comment by GitSquared** [comment]
@chaseWilliams Electron has two processes; "main" and "renderer" (Chromium window). In eDEX, the main process script is [`_boot.js`](https://github.com/GitSquared/edex-ui/blob/master/src/_boot.js) and the renderer is [`_renderer.js`](https://github.com/GitSquared/edex-ui/blob/master/src/_renderer.js).

The main process loads up the settings, starts the terminal backend *(and some multithreading helpers, but you don't need to worry about that)*, and create a window that loads up [`ui.html`](https://github.com/GitSquared/edex-ui/blob/master/src/ui.html) and all the renderer scripts in order. The window definition is here:

https://github.com/GitSquared/edex-ui/blob/ce4555259c197d673711c35630339eef7545128a/src/_boot.js#L162-L193

These options are documented [here](https://electronjs.org/docs/api/browser-window).

`ui.html`, the renderer process entrypoint, links to all the CSS & JS files needed for each "module" (Clock, GeoIP globe, etc), provides a blank "init" HTML state, then starts the main renderer script which initializes everything:

https://github.com/GitSquared/edex-ui/blob/ce4555259c197d673711c35630339eef7545128a/src/ui.html#L58

---

So, **to achieve what you want to do**, you'll need to:

 - **Get rid of everything you don't need in your widgets.**
   - Remove all the code in both processes relating to the terminal emulator (look for keywords `pty`, `xterm`)
   - Same thing for the file browser (fsDisp/filesystem) and the touch keyboard.
   - Remove anything related to what is internally called `modal`s, which are little pop-up windows used to display errors, settings editors, etc.
   - Delete anything that registers keyboard shortcuts (`globalShortcuts` is the Electron API used), to prevent unexpected behavior when you'll be using other apps.
   - I think that's it but you should probably skim through the whole renderer script and if it's not twice smaller by the time you're done, you probably missed something.
 - **Change the structure of the app to have 2 different renderer scripts.**
   - Basically, clone the `ui.html` and `_renderer.js` files that you just edited, rename the clones so you have like `ui-left` and `ui-right` files,
   - And remove stuff (again) in each file so that one of them loads up all the modules of the "System" panel, and the other one loads the "Network" panel. [Relevant code](https://github.com/GitSquared/edex-ui/blob/ce4555259c197d673711c35630339eef7545128a/src/_renderer.js#L389-L403).
   - Edit some CSS to make everything work.
 - **Edit the main process script to start 2 windows.**
   - Pretty much it. One window for each panel.
   - You'll also need to edit the options of the windows to remove the fullscreen, position them on your screen, and I believe Electron has a transparent window option so you might be interested in trying it out.

That's about it. **Most of the work is just deleting a bunch of stuff** - then sticking the remaining parts together with a bit of glue. If I were to give an estimate, I'd say within 2 hours you should be able to get something interesting running - with a bit of polishing needed afterwards, perhaps.

I hope this also makes it clearer why I don't want to include this as an option in the app - it would need to skip through half the codebase, essentially building 2 very different apps in one messy package.

If you're adventurous enough to do this but struggle at some point, don't hesitate to reach out for more help - my email is on [gaby.dev](https://gaby.dev).

I will mark this issue `wontfix`.
