### ISSUE TITLE
Globe pins property error

### ISSUE THREAD

**Issue by militaryCoder** [GitSquared/edex-ui#599]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [x] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

### Disclaimer
So, I'm running eDEX under MacOS 10.11.6 and maybe this fact can cause this problem.
---
### Problem itself
The problem is when I start eDEX-UI, it print message box like this:

![image](https://user-images.githubusercontent.com/55032128/67051465-d0d16f00-f143-11e9-8ff5-6bb00acdea72.png)

Due to this error the globe doesn't appear at all (panel where the globe is supposed to be just saying that I'm offline but my Internet connection is stable).

![image](https://user-images.githubusercontent.com/55032128/67051580-286fda80-f144-11e9-927c-261c16c7f390.png)

As I see, an error appears in `locationGlobe.class.js, 1:4129`, so I think you can try to start digging there (If I were better developer, I would try to fix this issue myself but indeed I'm not).

**Comment by militaryCoder** [comment]
Strange error because there is no 4129th symbol in the 1st string.

**Comment by GitSquared** [comment]
@militaryCoder This is because the release code is minified. I'll investigate this tomorrow.

**Comment by GitSquared** [comment]
Sorry for the delay. I traced the error back to this line (`v2.2.2` branch):
https://github.com/GitSquared/edex-ui/blob/590c67518a2c3fc3f0f1f0c6adc401c763b1d516/src/classes/locationGlobe.class.js#L191

So it seems in your case `this.globe` was undef, which means this failed:
https://github.com/GitSquared/edex-ui/blob/590c67518a2c3fc3f0f1f0c6adc401c763b1d516/src/classes/locationGlobe.class.js#L31-L46

This probably means that the WebGL context couldn't be initialized, possibly because of some GPU problem.
@militaryCoder Could you tell me what hardware+software you were running this on?

**Comment by militaryCoder** [comment]
@GitSquared I'm using **MacBook Pro** under MacOS **10.11.6** which is installed with **Intel Core i52.3 GHz**, **8 Gb RAM DDR3 1333 MHz** and **Intel HD Graphics 3000 with 512 Mb VRAM**.

**Comment by GitSquared** [comment]
@militaryCoder Thanks for the info. You're experiencing a GPU compatibility bug that was fixed upstream, unfortunately you'll need to wait for the next eDEX release to get the fix - or you could try building from source.
