### ISSUE TITLE
Please tell us how to change the advanced settings for themes

### ISSUE THREAD

**Issue by Footsiefat** [GitSquared/edex-ui#663]
So you have explained the basics very well, but you haven't explained (on the wiki) how to inject stuff with <style> tags, like if I wanted to change how it greeted me how would I change that text? There is currently nothing that can help people learn to how make that sort of modification, I would highly appreciate it if you showed in the wiki (potentially with examples) how to change the more interacate parts of this program and maybe show specific settings rather than just saying you can use <style> to do stuff.

Many thanks, 
Paul

**Comment by GitSquared** [comment]
Hi Paul,

Glad you're interested in this! The `injectCSS` property in themes is a very powerful feature that serves as a placeholder for more accessible customization settings (like custom modules and UI layouts) that should be released at some point in the future.

**Injecting style rules is hacking.** You're adding your own extra sauce on top of the source code. You need to override previous styles, new releases can break all your modifications at once, and the code you end up writing will be [ugly](https://github.com/GitSquared/edex-ui/blob/80c5fbfd508c4779f5281a0bf8e752a1ed76bb0c/src/assets/themes/tron-disrupted.json#L29).
Which is why there are no examples in the wiki, only suggestions of what you could do.

If you're *(very) comfortable with CSS*, know your way around a web browser's dev tools, and have an hour to spare, you can pop-up said dev tools in eDEX with `Ctrl+Shift+I`. From there you can just edit all the CSS you like, and write down your final modifications in a theme - easier said than done.

Otherwise, from an end-user standpoint, you effectively can't change the greeting text or do other advanced customization as those are not currently supported features.

Hope this helps.
