### ISSUE TITLE
Got edex-ui working on Raspberry Pi 4 running 64bit Ubuntu 19.10

### ISSUE THREAD

**Issue by jzellis** [GitSquared/edex-ui#702]
I really, really wanted to get Edex working on my old Raspberry Pi 3B with the touchscreen, but alas, I could never hack it to work properly. But it works on 64 bit Ubuntu 18.04 and 19.10 on the Pi 4 perfectly!

The only thing I had to do was replace `x64` with `aarch64` everywhere in package.json. Then I just ran the install script for Linux and it worked perfectly out of the gate! No build required or anything. As long as you’re running a 64 bit OS on either the Pi 3 or 4, it should work fine.

Unfortunately, I discovered that the keyboard is just too small to use with the Pi touchscreen, and since I haven’t added a cooling fan to mine, it got pretty hot pretty quick running nothing but edex and Enlightenment as my desktop. But it looks cool as hell!

I think I’m going to make my own xterm/node-pty electron app specifically for use with touchscreens, but inspired by Edex! And if you’re someone who just wants it on a Pi, and you’ve got a 64 bit OS, that’s all it takes.

![C85CE997-B02B-40BC-9152-213A23CDC9D0](https://user-images.githubusercontent.com/1280868/76141200-ce01e880-6016-11ea-9346-57346a4e2028.jpeg)

**Comment by GitSquared** [comment]
Thanks for sharing this!

Some reflections:

- You could use a custom theme (with CSS injections - see wiki) to resize the different elements so that the keyboard is usable.
- Building the app instead of just running from source *should* give you better performance as everything gets optimized in the process.
- If you want to try to further reduce CPU impact, you could dive into `src/` and:
  - Lower the refresh rate of the webgl globe
  - Set bigger time intervals for the data refresh calls in all modules (`setInterval`)
- How does a more performance-focused Electron term emulator like zeit/hyper performs on your Pi?

Lastly, if you're going to build an emulator yourself, please share it with us! :v:
