### ISSUE TITLE
Top processes not populating

### ISSUE THREAD

**Issue by paulcsiki** [GitSquared/edex-ui#750]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [X] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [X] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [X] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

Top processed doesn't seem to populate despite running the process as an administrator. I use a custom task manager - not sure if that changes anything (Process Hacker). A simple powershell "Get-Process" call works just fine and tasklist works too.

**Comment by GitSquared** [comment]
You should try to build edex from source to see if the issue has been fixed since 2.2.

If it still doesn't work, we leverage the `.processes()` call from the latest version of [systeminformation](https://github.com/sebhildebrandt/systeminformation) to list processes accross systems, so you might want to check in with them if you know your way around node libs.

**Comment by paulcsiki** [comment]
@GitSquared, thanks. I can confirm that the latest version still fails to pull the list of processes so I'll do some digging on this. Thanks for pointing out where to start.
