### ISSUE TITLE
Power type reported as "Wired" while on battery

### ISSUE THREAD

**Issue by the-garlic-os** [GitSquared/edex-ui#833]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [x] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem
I'm using a Lenovo laptop. While it's on battery, if I start up Edex, it will still say that my power status is "Wired", when I would expect it would say something like "Battery" instead.

My laptop is a Lenovo L380 Yoga TP00019A.

**Comment by parkerlreed** [comment]
Please test against master

https://github.com/GitSquared/edex-ui/issues/769

**Comment by wrac4242** [comment]
I have this issue on master branch, running on a windows laptop

**Comment by GitSquared** [comment]
Sounds a lot like sebhildebrandt/systeminformation#145, but this was fixed years ago... Will check this out.

**Comment by wrac4242** [comment]
done some testing, the main code to check this is [here](https://github.com/GitSquared/edex-ui/blob/master/src/classes/sysinfo.class.js), in line 125, 
`                } else if (bat.acconnected || bat.timeremaining === -1) {`

the issue is caused by `bat.timeremaining` I belive
due to it being the only thing set, and when removed correctly displays battery percentage

**Comment by GitSquared** [comment]
mind submitting a PR?
