### ISSUE TITLE
Spotify integration

### ISSUE THREAD

**Issue by Benimautner** [GitSquared/edex-ui#835]
Hi!

I've been working on an implementation to have basic controls over Spotify playback directly from edex-ui.
I'd like to know if you are interested in such a feature and if I should clean up my code so you can merge it with your master branch.
As this is a feature which not everyone would need I would like to know if I should add an option which completely disables the whole thing.

And lastly, just because I haven't understood it yet, how are icons handled in edex? I am building my HTML when initializing the instance of the class right now but I haven't found a way to add an icon to it.

BM

**Comment by GitSquared** [comment]
Always nice to see people hacking on this! Thanks for taking a shot at it. Don't hesitate to send a gif demo :eyes: 

> I'd like to know if you are interested in such a feature and if I should clean up my code so you can merge it with your master branch.

- Is there a UI element to this? If so, where did you put it on the screen?
- Does it work on all 3 platforms supported by eDEX? (Win32+Darwin+Linux)
- Could this be generalized to work with other services than Spotify? For example, to leverage OS-level music controls? Electron APIs should allow us to do that I think. I would be against a feature that depends on an external service, especially a for-profit one.

> And lastly, just because I haven't understood it yet, how are icons handled in edex?

The only place where icons are used - if I remember right - is in the filesystem widget, codename `fsDisp`. You should check in there, maybe you can leverage some icons from it.

**Comment by Benimautner** [comment]
> Is there a UI element to this? If so, where did you put it on the screen?
Yes. But as I haven't done a whole lot, just added one line to test the Spotify API.
I removed the keyboard because I didn't need it and then just appended it to the `mod_column_right`

> Does it work on all 3 platforms supported by eDEX? (Win32+Darwin+Linux)
I haven't tried Win32 and Darwin yet. Is there some clever way to do that or would I have to manually test it?

> Could this be generalized to work with other services than Spotify?
Yes definitely, that's what I've been thinking, too. The thing is, though, that I wanted to use the Spotify API to control Spotify without the need of a local Spotify client. But I could add settings to switch between media controls and the Spotify API. (one could even integrate different APIs by writing a clever class that supports that...)

**Comment by GitSquared** [comment]
> Yes. But as I haven't done a whole lot, just added one line to test the Spotify API.
I removed the keyboard because I didn't need it and then just appended it to the mod_column_right

I'm not sure where it could fit if we don't remove anything, but you're going to have to think about that if you plan on submitting a PR here.

> I haven't tried Win32 and Darwin yet. Is there some clever way to do that or would I have to manually test it?

Unfortunately none that I know of. When I worked on this I checked all the APIs I was using were compatible with each platform, and just spun up VMs before making a release, to make sure it worked.

> Yes definitely, that's what I've been thinking, too. The thing is, though, that I wanted to use the Spotify API to control Spotify without the need of a local Spotify client. But I could add settings to switch between media controls and the Spotify API.

To be extra clear: I'm unfortunately not going to be able to merge anything that has the "Spotify" name in the diff.

**Comment by takoyaro** [comment]
Came here because I'm currently using [spotify-tui](https://formulae.brew.sh/formula/spotify-tui) and I'm looking for a way to turn off the ticking sounds every time the spotify-tui UI is refreshed without turning the sound off for everything in EDEX. Having a Spotify UI native to EDEX would be a blessing!

**Comment by GitSquared** [comment]
> I'm looking for a way to turn off the ticking sounds

Check the `disableFeedbackAudio` in the [settings](https://github.com/GitSquared/edex-ui/wiki/settings.json)

**Comment by GitSquared** [comment]
Closed as stale.
