### ISSUE TITLE
World View+Network Traffic/Status Not Working

### ISSUE THREAD

**Issue by Jaruude** [GitSquared/edex-ui#843]
I have just installed the Edex-ui and allowed it through the firewall but no matter how many google searches I cannot find any information to get it to work. I have checked on the Issue tab to see if someone has had the same problem as me but the best I could get was faint hints as to what they did to get it to work. 

I was hoping if someone could throw me a bone to go looking in the right direction to fix it or if they could help me.
I am fairly new and will be a bit slow in getting to understanding things.

This is what it looks like, side note I dont know why it also goes blurry? When I click in the selected area it becomes unblurry witch is odd.
![image](https://user-images.githubusercontent.com/74007852/98257367-47781f00-1f88-11eb-9c23-7084ca256a60.png)

**Comment by chicharituz** [comment]
hello there, had the same issue, just open de settings file, and in the new windows that pop ups, where it says pingaddr, you´ll see it´s pinging 1.1.1.1 which is your own computer, change that to www.google.com or some other page, so that it can validate connectivity, save to disk, and that´s all, the network status will come to life, so does the world view

have a good one

**Comment by edonisth** [comment]
Hi there. I apologize to accidentally make myself a part of this chat.
Could someone help me how I can stop receiving emails. Goodluck to u guys!

**Comment by GitSquared** [comment]
@edonisth Go to [the repo's homepage](https://gaby.dev/edex), and click "Unwatch" in the top right of the window, next to the sponsor button.

**Comment by GitSquared** [comment]
> hello there, had the same issue, just open de settings file, and in the new windows that pop ups, where it says pingaddr, you´ll see it´s pinging 1.1.1.1 which is your own computer, change that to [www.google.com](http://www.google.com) or some other page, so that it can validate connectivity, save to disk, and that´s all, the network status will come to life, so does the world view
> 
> have a good one

`1.1.1.1` is Cloudflare's open DNS service, if those are blocked/not accessible in your region I recommend you switch to Quad9 `9.9.9.9` or Google `8.8.8.8`. If you're in China chances are you'll need to setup a Baidu/Tencent address because the other ones may be unaccessible.

Alternatively, check in the settings `Ctrl+Shift+S` that the `iface` parameter is setup to the correct network interface.
