### ISSUE TITLE
Add the option to disable the constant recalculation of available disk space in settings.

### ISSUE THREAD

**Issue by jmdeejay** [GitSquared/edex-ui#844]
It would be awesome to have a settings to disable recalculation of disk space & only calculate it once at the startup of the application & that's it... Instead of recalculating it at every single move: 

- folder change: recalculate,
- window change: recalculate,
- modifying a file: recalculate

I think this is the main reason I have a slow experience on my laptop.

**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [ X ] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [ X ] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

**Comment by parkerlreed** [comment]
As far as I know available disk space is just taken from df output, which doesn't take a lot of time at all.

The slowness probably just comes from eDEX using Electron and working better with beefier graphics cards/processors.

**Comment by GitSquared** [comment]
> with beefier graphics cards/processors.

To expand on that, the main performance factor is how many threads/cores you have on the CPU.

> I think this is the main reason I have a slow experience on my laptop.

Disk space calculations are cached at the operating system level so it's unlikely that this is the main reason.
Because it's retrieved asynchronously it's likely to display with a bit of lag if you're having general performance issues with the app, but it's only a symptom, not a cause.
