### ISSUE TITLE
Mac OS - edex keeps focus when pasting with cmd-v

### ISSUE THREAD

**Issue by pitichampi** [GitSquared/edex-ui#847]
## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [x] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

I have not been able to define clearly when it happens but sometimes (pretty often btw) when I copy something to my clipboard (with mouse, keyboard or any other way), if I try to paste it in any application, the terminal of edex keeps the focus and the content is pasted in the term even if the window is not focused at all (not even displayed because on a different virtual desktop).
I'm running on a Mac mini late 2014 with macOS 10.13.6

**Comment by GitSquared** [comment]
Yeah this shouldn't happen... Maybe some blur/focus events are not being sent because you're switching desktops or something? (I never understood how fullscreen apps work in macOS, "desktops" may not be the right wording)

https://github.com/GitSquared/edex-ui/blob/048feb502b2b3b1ccd3ad8e3484d1b22cfe8766a/src/_renderer.js#L1076-L1083

**Comment by kooshlash** [comment]
Bye than
