### ISSUE TITLE
Error: ENOSPC: no space left on device...

### ISSUE THREAD

**Issue by herunotenchi** [GitSquared/edex-ui#851]
## Technical information
 - v2.2.2

**Running on:**
 - Linux (KDE Neon 5.20 64bit)

**How comfortable you are with your system and/or IT in general:**
 - My machine is fully under my control, tell me what you need, 

---

## Problem

By typing in terminal or clicking on folders result is the same, changing direcotry leads to ENOSPC error from watcher.js

Filesystem tested: ext4, fat, ntfs (same results)
HDD types: SSD, SSHD, HDD and M2 (same results)

System: KDE Neon User Edition - 5.20 / x86_64
DE: Plasma
WM: KWin
Kernel: 5.40.0-52-generic
Shell: bash 5.0.17

--

Hardware: i7-8700 / 32 GB / Nvidia RTX 2070

**Comment by ntando-lab** [comment]
I need money

**Comment by KitGlass** [comment]
```

```

**Comment by GitSquared** [comment]
so... do you actually have any space left?

**Comment by herunotenchi** [comment]
yes, only one of my partitions got bout 92% place taken, so... 
what I realize this is problem shows up sometimes, but if once happen then it's to the end, you must close app and start again, sometimes it's form begining and sometimes after some time, i'm looking at way to reproduce it constantly.

**Comment by GitSquared** [comment]
> i'm looking at way to reproduce it constantly.

Please reopen if you manage to do that - and on edex v3.

**Comment by CodeGrammer45** [comment]
I am having this same issue. The issue happens for me at any directory change using the default shell.

By default, the shell is Bash, and any directory change produces the following:

> Error: ENOSPC: no space left on device, watch [PWD]
Uncaught Error: ENOSPC: no space left on device, watch [PWD]
at internal/fs/watchers.js 170:5

This is on Pop!_OS 20.04, and there is plenty of space left on the device.

The really weird thing is this:
This happens in the **default shell only.** So if default shell is Bash, and I switch to ZSH by issuing the command `zsh`, then this issue is no longer present. I thought it must be a Bash problem. However, I changed the default shell to ZSH, and now it does it until I switch to Bash!
