### ISSUE TITLE
high energy cost

### ISSUE THREAD

**Issue by Weilory** [GitSquared/edex-ui#884]
<img width="960" alt="Screen Shot 2020-11-12 at 4 17 11 pm" src="https://user-images.githubusercontent.com/54391313/98898816-91ba4c80-2502-11eb-899d-163a423547c2.png">

running vim on UI for 10 minutes reduce my power from 40% to 27%

**Comment by GitSquared** [comment]
What model of macbook, and how old?

**Comment by Weilory** [comment]
<img width="585" alt="Screen Shot 2020-11-12 at 8 44 16 pm" src="https://user-images.githubusercontent.com/54391313/98923524-ddcbb800-2527-11eb-85f2-b6a28b1d2377.png">

First thank you for creating such badass and incredible ui and hosting it as ** open-source **, I would like to donate. :smile:
eDEX-UI runs at a normal power consumption if I only run terminal. However, as vim is launched the fans go very loud and the keyboard heat figures. as I editing my scripts in vim, the power rapidly went down. I wonder if something is overloading. 

<hr />
During the fans go loud, I recorded following data from Activity Monitor

CPU: 
1. Occupation: 43%
1. Time: 2:08:26
1. Thread: 8
1. IDE Wake Ups: 176
1. PID: 490
1. GPU: %0

Memory
1. memory: 840MB
1. Thread: 9
1. Ports: 163
1. PID: 471

**Comment by Weilory** [comment]
I suggest two possible reasons:

1. the disc image file is downloaded from web browser instead of a formal application from App Store, which triggers alertness from anti-malware protection. 

2. random memory is not properly handled. I notice it takes longer when I run `clear RAM` before shutting done my Mac if I previously had run eDEX.

**Comment by Weilory** [comment]
The energy cost is tremendous man, I fully charged Mac to 100% on 7:30 and I wrote scripts on eDEX-UI with Vim for only 3 hours, the battery is 6% left. :sweat_smile:

The keyboard was crazy hot, I guess it makes energy consumption larger by running the fan heat-releasing system.

**Comment by GitSquared** [comment]
eDEX is tuned for performance. It will try to spread its workload across all cores/threads of your processor, and the graphics are accelerated by your GPU. On most systems this works fine and makes it run smoothly.

Unfortunately you've got an 8-cores beast of a CPU, baseline rated at 45W, crammed in a slim laptop... As edex's work keeps all 16 threads constantly working in the background, it drains power like crazy.

I'm afraid I can't do much to help at the software level. Normally to fix these kind of issues you'd adjust the frequency response of your CPU, limiting how fast it can go, or making it accelerate slower so it doesn't jump to max speed for only a second. Then you undervolt it, meaning reduce the maximum amount of power it can drain from your system.

I'm not even sure your Mac's hardware will let you do those things (because, well, it's Apple). I guess you're just unlucky on this one.

**Comment by Weilory** [comment]
Find suitable solution for multicore OSX: https://www.whatroute.net/cpusetter.html

**Comment by tomByrer** [comment]
> battery is 6% left

Ouch
You could fork this repo, then try to disable the parts you don't care about (eg the keyboard & globe for me) to get a bit of extra life.

But Electron is not the the most lightweight app shell out there.  IIRC Discord is/was written on Electron also, & some had CPU complaints.
